<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>04792db0-34b6-438d-8529-eb9f177a1e88</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pri.EindOpdracht.ApiConsumer\Pri.EindOpdracht.ApiConsumer.csproj" />
  </ItemGroup>

</Project>
