// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pri.EindOpdracht.Core.Data;

#nullable disable

namespace Pri.EindOpdracht.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241224150347_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ed242992-0a90-4bf0-88ef-ee3dcceb4cb3",
                            Email = "admin@example.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMYJWZe7eclQN3r/ehikytl1R7pZNLoN4uaMtbJUqlxxyt+X2oFltT+YB3HVqqkHaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7863e2fc-3b7c-4480-b5e6-8c274848f666",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e466e9bf-10ae-4a8f-b449-e24e07c56f51",
                            Email = "customer1@example.com",
                            EmailConfirmed = false,
                            FirstName = "Customer",
                            LastName = "One",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER1@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEOu37gvod5yUxURqULd0+sevTU72rGEAVK0DZ8gRwrEpcEvDYAtEMJUu9dfh5g9IjQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a86c99f9-c2b1-4ce2-a934-d0d1ccf134a5",
                            TwoFactorEnabled = false,
                            UserName = "customer1"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "85fa5873-4c16-468e-8b26-5d91280325b6",
                            Email = "customer2@example.com",
                            EmailConfirmed = false,
                            FirstName = "Customer",
                            LastName = "Two",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER2@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEB3obaEenMSiQfenll/FpIMjdmuF8zzVtd8adCOzFlB24gsMI2uOVG8ezERWqksYfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6f47b02-ffcc-4f4f-aaaa-60dc8b3795b0",
                            TwoFactorEnabled = false,
                            UserName = "customer2"
                        });
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Achieved")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Achieved = false,
                            Description = "Run 5 km in 30 minutes",
                            TargetDate = new DateTime(2025, 1, 24, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6128),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 2,
                            Achieved = false,
                            Description = "Lose 5 kg in 2 months",
                            TargetDate = new DateTime(2025, 2, 24, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6136),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3,
                            Achieved = false,
                            Description = "Do 50 push-ups in one go",
                            TargetDate = new DateTime(2025, 3, 24, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6139),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 4,
                            Achieved = false,
                            Description = "Run 10 km in 60 minutes",
                            TargetDate = new DateTime(2025, 1, 24, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6141),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 5,
                            Achieved = false,
                            Description = "Gain 3 kg of muscle in 3 months",
                            TargetDate = new DateTime(2025, 3, 24, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6144),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 6,
                            Achieved = false,
                            Description = "Hold a plank for 5 minutes",
                            TargetDate = new DateTime(2025, 2, 24, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6147),
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkoutTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutTypeId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesBurned = 250,
                            Date = new DateTime(2024, 12, 23, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(5995),
                            Duration = 30,
                            UserId = "2",
                            WorkoutTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CaloriesBurned = 350,
                            Date = new DateTime(2024, 12, 22, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6050),
                            Duration = 45,
                            UserId = "2",
                            WorkoutTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CaloriesBurned = 100,
                            Date = new DateTime(2024, 12, 21, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6053),
                            Duration = 20,
                            UserId = "2",
                            WorkoutTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            CaloriesBurned = 200,
                            Date = new DateTime(2024, 12, 23, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6056),
                            Duration = 25,
                            UserId = "3",
                            WorkoutTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            CaloriesBurned = 300,
                            Date = new DateTime(2024, 12, 22, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6058),
                            Duration = 40,
                            UserId = "3",
                            WorkoutTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            CaloriesBurned = 80,
                            Date = new DateTime(2024, 12, 21, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6068),
                            Duration = 15,
                            UserId = "3",
                            WorkoutTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            CaloriesBurned = 270,
                            Date = new DateTime(2024, 12, 24, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6071),
                            Duration = 35,
                            WorkoutTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CaloriesBurned = 400,
                            Date = new DateTime(2024, 12, 24, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6073),
                            Duration = 50,
                            WorkoutTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            CaloriesBurned = 120,
                            Date = new DateTime(2024, 12, 24, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6076),
                            Duration = 25,
                            WorkoutTypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            CaloriesBurned = 500,
                            Date = new DateTime(2024, 12, 24, 16, 3, 46, 761, DateTimeKind.Local).AddTicks(6079),
                            Duration = 60,
                            WorkoutTypeId = 1
                        });
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.WorkoutType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Boost your heart rate and endurance",
                            Difficulty = "Intermediate",
                            Name = "Cardio"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Build muscle and strength",
                            Difficulty = "Advanced",
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Improve range of motion and posture",
                            Difficulty = "Beginner",
                            Name = "Flexibility"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.Goal", b =>
                {
                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.Workout", b =>
                {
                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId");

                    b.HasOne("Pri.EindOpdracht.Core.Entities.WorkoutType", "WorkoutType")
                        .WithMany("Workouts")
                        .HasForeignKey("WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutType");
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.WorkoutType", b =>
                {
                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
