// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pri.EindOpdracht.Core.Data;

#nullable disable

namespace Pri.EindOpdracht.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2025, 1, 2, 21, 41, 43, 901, DateTimeKind.Local).AddTicks(4687),
                            ConcurrencyStamp = "074e9401-82e4-4e27-9260-6e7c2d6d44d9",
                            Email = "admin@example.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEBCl6Dj2X7qolUdIzkp3+ot9s4Suc7hSPnNtccb/FTw4IS5crwI0CkVPu3uTJcudkA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c120a3ce-421c-42c1-8741-85ea25edecba",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2025, 1, 2, 21, 41, 43, 977, DateTimeKind.Local).AddTicks(6530),
                            ConcurrencyStamp = "efdd4618-3c5e-4050-b224-cc7f6c7a1f82",
                            Email = "customer1@example.com",
                            EmailConfirmed = false,
                            FirstName = "Customer",
                            LastName = "One",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER1@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEIZppWjwEUZWZvnaVJsaA+HgdrZq/83CoBFO2+FjXRsJoH5E42yE2BPmfoQ6Q3jvUQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "69d6df94-5bef-4143-92fe-9649c1417d85",
                            TwoFactorEnabled = false,
                            UserName = "customer1"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2025, 1, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(2695),
                            ConcurrencyStamp = "304fa80f-e52d-48e1-afed-3c32af45810c",
                            Email = "customer2@example.com",
                            EmailConfirmed = false,
                            FirstName = "Customer",
                            LastName = "Two",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER2@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEGvd5SgF43MjlqZ7tWYpc0OSmxZksyWbR8i80yMRwFOAcix6VkBYrOk/V2nGt1gFgQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3510cd3-2a39-4ef6-ae35-b3c6bdc9d1a8",
                            TwoFactorEnabled = false,
                            UserName = "customer2"
                        });
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Achieved")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Achieved = false,
                            Description = "Run 5 km in 30 minutes",
                            TargetDate = new DateTime(2025, 2, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3609),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 2,
                            Achieved = false,
                            Description = "Lose 5 kg in 2 months",
                            TargetDate = new DateTime(2025, 3, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3617),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3,
                            Achieved = false,
                            Description = "Do 50 push-ups in one go",
                            TargetDate = new DateTime(2025, 4, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3621),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 4,
                            Achieved = false,
                            Description = "Run 10 km in 60 minutes",
                            TargetDate = new DateTime(2025, 2, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3623),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 5,
                            Achieved = false,
                            Description = "Gain 3 kg of muscle in 3 months",
                            TargetDate = new DateTime(2025, 4, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3626),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 6,
                            Achieved = false,
                            Description = "Hold a plank for 5 minutes",
                            TargetDate = new DateTime(2025, 3, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3630),
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkoutTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutTypeId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesBurned = 250,
                            Date = new DateTime(2025, 1, 1, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3509),
                            Duration = 30,
                            UserId = "2",
                            WorkoutTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CaloriesBurned = 350,
                            Date = new DateTime(2024, 12, 31, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3525),
                            Duration = 45,
                            UserId = "2",
                            WorkoutTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CaloriesBurned = 100,
                            Date = new DateTime(2024, 12, 30, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3529),
                            Duration = 20,
                            UserId = "2",
                            WorkoutTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            CaloriesBurned = 200,
                            Date = new DateTime(2025, 1, 1, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3532),
                            Duration = 25,
                            UserId = "3",
                            WorkoutTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            CaloriesBurned = 300,
                            Date = new DateTime(2024, 12, 31, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3534),
                            Duration = 40,
                            UserId = "3",
                            WorkoutTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            CaloriesBurned = 80,
                            Date = new DateTime(2024, 12, 30, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3549),
                            Duration = 15,
                            UserId = "3",
                            WorkoutTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            CaloriesBurned = 270,
                            Date = new DateTime(2025, 1, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3552),
                            Duration = 35,
                            UserId = "2",
                            WorkoutTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CaloriesBurned = 400,
                            Date = new DateTime(2025, 1, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3555),
                            Duration = 50,
                            UserId = "2",
                            WorkoutTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            CaloriesBurned = 120,
                            Date = new DateTime(2025, 1, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3557),
                            Duration = 25,
                            UserId = "2",
                            WorkoutTypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            CaloriesBurned = 500,
                            Date = new DateTime(2025, 1, 2, 21, 41, 44, 49, DateTimeKind.Local).AddTicks(3561),
                            Duration = 60,
                            UserId = "2",
                            WorkoutTypeId = 1
                        });
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.WorkoutType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Boost your heart rate and endurance",
                            Difficulty = "Intermediate",
                            Name = "Cardio"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Build muscle and strength",
                            Difficulty = "Advanced",
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Improve range of motion and posture",
                            Difficulty = "Beginner",
                            Name = "Flexibility"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.Goal", b =>
                {
                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.Workout", b =>
                {
                    b.HasOne("Pri.EindOpdracht.Core.Entities.ApplicationUser", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.EindOpdracht.Core.Entities.WorkoutType", "WorkoutType")
                        .WithMany("Workouts")
                        .HasForeignKey("WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutType");
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Pri.EindOpdracht.Core.Entities.WorkoutType", b =>
                {
                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
